export type GuideSection = { heading: string; paragraphs: string[] };
export type EditorialGuide = {
 slug: string; title: string; excerpt: string; category: string; readTime: string; sections: GuideSection[];
};

const commonClosing = [
 "Les prix et la disponibilité changent selon le marchand et la date du relevé. Une comparaison utile ne remplace donc pas la vérification de la fiche du vendeur : frais de livraison, garantie, accessoires inclus et conditions de retour peuvent modifier le coût réel.",
 "Sur Soumly, utilisez les offres comme point de départ : comparez la même référence, vérifiez les caractéristiques importantes et ouvrez le lien marchand avant de valider votre achat. La méthode complète est expliquée dans la page Méthodologie.",
];

export const editorialGuides: EditorialGuide[] = [
 {slug:"choisir-smartphone-tunisie",title:"Comment choisir un smartphone en Tunisie",excerpt:"Les critères réellement utiles pour choisir un téléphone adapté à votre usage et comparer des offres équivalentes en Tunisie.",category:"Smartphones",readTime:"8 min",sections:[
  {heading:"Commencer par l’usage",paragraphs:["Un smartphone pour WhatsApp, les appels et la photo familiale n’a pas les mêmes besoins qu’un appareil destiné au jeu, au montage vidéo ou à une longue journée de travail. Notez les applications importantes, la fréquence des déplacements et la durée pendant laquelle vous souhaitez garder le téléphone. Ce cadrage évite de payer pour une fonction rarement utilisée."]},
  {heading:"Écran, autonomie et réseau",paragraphs:["La taille et la luminosité de l’écran comptent beaucoup en extérieur. Une batterie plus grande aide, mais l’optimisation du processeur et du logiciel compte également. En Tunisie, vérifiez la compatibilité 4G ou 5G avec votre opérateur, les bandes annoncées et la présence d’un chargeur adapté. La charge rapide est pratique, mais regardez aussi le coût d’un remplacement de batterie."]},
  {heading:"Mémoire, stockage et appareil photo",paragraphs:["Pour un usage courant, 6 Go de RAM et un stockage confortable peuvent suffire, tandis que les jeux et le multitâche profitent de davantage de mémoire. Un capteur avec beaucoup de mégapixels ne garantit pas de meilleures photos : traitement logiciel, stabilisation et qualité en basse lumière sont plus révélateurs. Vérifiez aussi si le stockage peut être étendu."]},
  {heading:"Comparer une vraie référence",paragraphs:["Les variantes d’un même modèle peuvent changer selon la RAM, la capacité, la couleur ou la région. Avant de comparer deux prix, lisez le nom complet et la référence. Soumly regroupe les offres qui correspondent à une même fiche, mais la page du marchand reste la référence pour la garantie, la disponibilité et les accessoires réellement inclus."]},
  {heading:"Budget et achat responsable",paragraphs:["Fixez un budget maximum et gardez une marge pour une coque, un verre de protection ou une livraison. Un modèle légèrement moins puissant mais mieux suivi par les mises à jour peut être plus intéressant sur plusieurs années. Les promotions très fortes doivent être vérifiées : prix final, produit neuf ou reconditionné, garantie et politique de retour."]},
 ]},
 {slug:"choisir-ordinateur-portable",title:"Quel ordinateur portable choisir",excerpt:"Un guide pratique pour distinguer les configurations bureautiques, étudiantes, créatives et gaming disponibles en Tunisie.",category:"Informatique",readTime:"8 min",sections:[
  {heading:"Définir le travail attendu",paragraphs:["Navigation, documents et visioconférence demandent moins de ressources que la programmation lourde, la retouche photo ou le jeu. Listez les logiciels utilisés et leur fréquence. Cette étape est plus fiable qu’un choix basé uniquement sur la marque ou l’apparence. Un bon ordinateur est celui qui reste confortable dans votre usage quotidien, pas forcément celui qui a la fiche technique la plus impressionnante."]},
  {heading:"Processeur et mémoire vive",paragraphs:["Le processeur influence la réactivité et le temps nécessaire pour les tâches longues. Comparez une génération à l’autre avec prudence : la gamme et le nombre de cœurs ne racontent pas tout. Pour un ordinateur polyvalent, 8 Go de RAM est un minimum courant ; 16 Go offre davantage de confort pour les onglets, la création et les environnements de développement. Vérifiez si la mémoire est extensible."]},
  {heading:"SSD, écran et mobilité",paragraphs:["Un SSD rend le démarrage et les applications plus rapides qu’un disque mécanique. La capacité doit tenir compte des fichiers et des jeux : 256 Go peut devenir étroit. Pour le travail, regardez la lisibilité, la résolution, le clavier et le poids. Une machine plus légère peut avoir une autonomie ou un refroidissement différents ; comparez ces compromis plutôt que le seul chiffre annoncé."]},
  {heading:"Carte graphique et refroidissement",paragraphs:["Une puce graphique intégrée suffit souvent pour la bureautique et la vidéo. Une carte dédiée devient pertinente pour le jeu, la 3D et certains logiciels créatifs, avec une consommation et un poids supérieurs. Vérifiez la mémoire vidéo, les sorties écran, le bruit et la qualité du refroidissement. Les performances annoncées ne garantissent pas le même résultat sur tous les jeux."]},
  {heading:"Comparer les offres",paragraphs:["Comparez exactement le processeur, la RAM, le SSD, la disposition du clavier, le système installé et la garantie. Deux annonces portant le même nom peuvent cacher des configurations différentes. Sur Soumly, ouvrez l’offre la moins chère puis vérifiez les frais, la disponibilité et le service après-vente chez le marchand tunisien."]},
 ]},
 {slug:"choisir-smart-tv",title:"Comment choisir une Smart TV",excerpt:"Taille, résolution, dalle et système connecté : les points à vérifier avant d’acheter une télévision en Tunisie.",category:"TV & Image",readTime:"7 min",sections:[
  {heading:"Choisir la bonne taille",paragraphs:["La distance entre le canapé et l’écran doit guider la diagonale. Une grande TV n’est intéressante que si la pièce permet de la regarder confortablement. Mesurez le meuble, les passages et l’angle de vision avant la commande. Pensez aussi au poids et au système de fixation si vous prévoyez une installation murale."]},
  {heading:"Résolution et technologie de dalle",paragraphs:["La 4K est devenue courante sur les diagonales moyennes et grandes, mais la qualité dépend aussi du contraste, de la luminosité et du traitement de l’image. LED, QLED et OLED n’offrent pas le même rendu ni le même prix. Pour une pièce très lumineuse, la luminosité compte ; pour les films le soir, le contraste et les noirs peuvent être prioritaires."]},
  {heading:"Système Smart et connectique",paragraphs:["Vérifiez les applications disponibles, la fluidité de l’interface et la durée probable des mises à jour. HDMI, eARC, USB, Wi‑Fi et Bluetooth doivent correspondre à vos appareils. Une TV avec peu de ports peut nécessiter un répartiteur. Vérifiez aussi les formats audio et vidéo compatibles avec votre box, votre console et votre système de son."]},
  {heading:"Jeu, sport et son",paragraphs:["Pour une console récente, cherchez un faible temps de réponse, un mode jeu et, si nécessaire, un HDMI adapté au taux de rafraîchissement recherché. Pour le sport, la fluidité et les angles de vision sont importants. Le son intégré reste souvent limité par l’épaisseur du téléviseur : prévoyez une barre de son si la clarté des dialogues est essentielle."]},
  {heading:"Comparer sans se tromper",paragraphs:["Le nom commercial doit être complété par la référence exacte, la taille et la région. Les prix peuvent varier selon la garantie et la livraison. Consultez les offres Soumly, puis confirmez la fiche technique et les conditions du vendeur avant de comparer une promotion avec un modèle d’une autre génération."]},
 ]},
 {slug:"ssd-vs-hdd",title:"Guide SSD vs HDD",excerpt:"Comprendre les différences de vitesse, capacité, résistance et prix avant de choisir un stockage.",category:"Informatique",readTime:"7 min",sections:[
  {heading:"Ce que change un SSD",paragraphs:["Un SSD utilise de la mémoire flash et n’a pas de pièces mécaniques. Il accélère le démarrage, l’ouverture des logiciels et la recherche de fichiers. Il est silencieux et résiste mieux aux chocs pendant le transport. Tous les SSD ne se valent pas : interface, contrôleur, cache et endurance peuvent expliquer des écarts de prix."]},
  {heading:"Quand un HDD reste utile",paragraphs:["Un disque dur mécanique offre souvent beaucoup de capacité pour un coût plus bas. Il peut convenir à l’archivage de photos, vidéos et sauvegardes qui ne sont pas ouvertes en permanence. Il est toutefois plus lent, plus sensible aux chocs et audible. Pour un ordinateur principal, un SSD système complété par un HDD peut être un compromis pratique."]},
  {heading:"Capacité et interfaces",paragraphs:["Avant l’achat, vérifiez le format : 2,5 pouces, M.2 SATA ou M.2 NVMe ne se montent pas dans les mêmes logements. La capacité annoncée est exprimée en unités commerciales et l’espace réellement disponible est inférieur. Consultez le manuel de l’ordinateur ou de la carte mère plutôt que de supposer la compatibilité."]},
  {heading:"Fiabilité et sauvegarde",paragraphs:["SSD et HDD peuvent tomber en panne. L’endurance annoncée d’un SSD aide à comparer les modèles, mais ne remplace pas une sauvegarde. Gardez au moins une copie séparée des documents importants. Pour un disque externe, protégez-le des chocs et débranchez correctement les supports avant de les transporter."]},
  {heading:"Quel choix pour quel usage ?",paragraphs:["Choisissez le SSD pour le système, les applications, un portable ou un poste réactif. Choisissez le HDD pour une grande bibliothèque à prix maîtrisé, idéalement comme stockage secondaire et sauvegardé. Dans tous les cas, comparez la garantie, l’interface, la capacité utile et le prix par gigaoctet, pas uniquement la vitesse maximale affichée."]},
 ]},
 {slug:"choisir-machine-laver",title:"Comment choisir une machine à laver",excerpt:"Capacité, essorage, dimensions et consommation : les critères importants pour un achat adapté au foyer tunisien.",category:"Électroménager",readTime:"7 min",sections:[
  {heading:"Capacité et installation",paragraphs:["Une petite capacité convient à une personne ou un couple, tandis qu’un foyer nombreux bénéficiera d’un tambour plus grand. Mesurez la largeur, la profondeur, la hauteur et l’espace nécessaire pour ouvrir le hublot. Vérifiez les arrivées d’eau, l’évacuation et l’accès lors de la livraison avant de choisir un modèle lourd."]},
  {heading:"Essorage et programmes",paragraphs:["Une vitesse d’essorage élevée extrait davantage d’eau, mais peut froisser certains textiles et augmenter le bruit. Les programmes rapides sont utiles pour une petite charge, pas forcément pour une machine pleine. Regardez les cycles réellement utiles : coton, délicat, laine, rinçage, température basse et départ différé. Une interface simple peut être plus pratique qu’une longue liste de modes."]},
  {heading:"Consommation et entretien",paragraphs:["La consommation dépend du programme, de la température et de la charge. Privilégiez les lavages à basse température lorsque le textile le permet et entretenez le filtre, le joint et le bac à lessive. L’accès aux pièces et la disponibilité du service après-vente comptent autant que la classe énergétique affichée."]},
  {heading:"Lave-linge séchant ou séparé",paragraphs:["Un appareil combiné économise de la place, mais le poids de séchage peut être inférieur au poids de lavage et les cycles sont plus longs. Deux appareils donnent souvent davantage de flexibilité si l’espace et le budget le permettent. Comparez la capacité de chaque fonction, pas uniquement le nombre inscrit sur la façade."]},
  {heading:"Vérifier l’offre tunisienne",paragraphs:["Comparez référence, capacité, dimensions, garantie, livraison et installation. Une offre moins chère peut exclure certains services. Sur Soumly, consultez les offres équivalentes puis ouvrez le site du marchand pour confirmer le stock et les conditions applicables à votre adresse."]},
 ]},
 {slug:"choisir-refrigerateur",title:"Comment choisir un réfrigérateur",excerpt:"Volume, organisation intérieure, congélateur et consommation : comment comparer les réfrigérateurs sans se limiter au prix.",category:"Électroménager",readTime:"7 min",sections:[
  {heading:"Volume et format",paragraphs:["Le volume utile doit correspondre au nombre de personnes et à vos habitudes de courses. Mesurez l’emplacement, les portes, les escaliers et l’espace de ventilation recommandé. Un modèle plus grand consomme et coûte davantage, mais un appareil trop petit conduit à un rangement inefficace et à des ouvertures fréquentes."]},
  {heading:"Froid ventilé ou statique",paragraphs:["Le froid ventilé limite la formation de givre et répartit mieux la température, avec un ventilateur et une consommation à prendre en compte. Le froid statique peut être plus simple et moins cher, mais demande un dégivrage périodique. L’organisation des clayettes, des bacs et de la porte influence directement le confort quotidien."]},
  {heading:"Congélateur et climat",paragraphs:["Vérifiez le volume du congélateur, le nombre de tiroirs et l’autonomie annoncée en cas de coupure. La classe climatique indique les températures ambiantes prévues pour le fonctionnement. Dans un logement chaud ou une cuisine peu ventilée, l’emplacement et la dissipation thermique sont essentiels pour éviter une surconsommation."]},
  {heading:"Bruit, entretien et garantie",paragraphs:["Un réfrigérateur fonctionne en continu : le niveau sonore devient important dans une cuisine ouverte. Nettoyez régulièrement les joints et laissez l’espace de ventilation recommandé. La garantie, le réseau de réparation et la disponibilité des pièces doivent être comparés avec le volume et les fonctions proposées."]},
  {heading:"Comparer le coût réel",paragraphs:["Le prix d’achat n’est qu’une partie du coût. Ajoutez livraison, installation éventuelle et consommation sur la durée. Comparez des modèles de même volume et de même technologie, puis confirmez la référence exacte chez le marchand tunisien avant l’achat."]},
 ]},
 {slug:"choisir-climatiseur",title:"Comment choisir un climatiseur",excerpt:"Puissance, pièce, inverter, entretien et installation : les points à contrôler pour un climatiseur adapté.",category:"Maison & Jardin",readTime:"7 min",sections:[
  {heading:"Dimensionner la puissance",paragraphs:["La surface n’est qu’un premier repère. Orientation, hauteur sous plafond, isolation, nombre d’occupants et appareils produisant de la chaleur modifient le besoin. Un appareil sous-dimensionné fonctionne sans atteindre confort, tandis qu’un appareil trop puissant peut multiplier les cycles courts. Demandez une estimation professionnelle pour une installation importante."]},
  {heading:"Inverter et usage quotidien",paragraphs:["La technologie inverter ajuste la puissance au lieu de fonctionner uniquement par marche-arrêt. Elle peut améliorer le confort sonore et la consommation lorsque l’appareil est correctement dimensionné. Comparez la plage de fonctionnement, le mode nuit, la télécommande et la disponibilité des pièces plutôt que de vous arrêter au mot inverter."]},
  {heading:"Installation et évacuation",paragraphs:["L’unité intérieure doit distribuer l’air sans souffler directement sur les personnes. L’unité extérieure a besoin d’un emplacement ventilé et accessible pour l’entretien. Vérifiez la longueur des liaisons, l’évacuation des condensats, la protection électrique et ce qui est inclus dans le prix du marchand."]},
  {heading:"Entretien et consommation",paragraphs:["Nettoyez les filtres régulièrement et faites contrôler l’installation si le refroidissement baisse. Fermez portes et fenêtres pendant le fonctionnement et utilisez une température raisonnable. La consommation dépend de la puissance, du réglage, de l’isolation et du temps d’utilisation ; la fiche énergétique ne suffit pas à prévoir votre facture."]},
  {heading:"Comparer les offres",paragraphs:["Comparez puissance, type de compresseur, garantie, installation, niveau sonore et service après-vente. Deux prix ne sont comparables que si la pose et les accessoires sont traités de la même façon. Ouvrez l’offre du vendeur pour confirmer le stock et les conditions locales."]},
 ]},
 {slug:"choisir-imprimante",title:"Comment choisir une imprimante",excerpt:"Jet d’encre, laser, réservoir, connectivité et coût par page : le guide pour choisir selon votre volume réel.",category:"Bureau",readTime:"7 min",sections:[
  {heading:"Estimer le volume d’impression",paragraphs:["Quelques documents par mois ne justifient pas les mêmes choix qu’un travail quotidien ou une petite activité professionnelle. Estimez pages noires, pages couleur, photos et scans. Une imprimante multifonction peut faire gagner de la place, mais vérifiez la qualité du scanner et la vitesse dont vous avez réellement besoin."]},
  {heading:"Jet d’encre ou laser",paragraphs:["Le jet d’encre convient souvent aux couleurs et aux photos, mais les cartouches peuvent coûter cher si l’appareil reste longtemps inutilisé. Le laser est généralement adapté aux documents texte et aux volumes réguliers. Les modèles à réservoir réduisent le coût d’encre à long terme, avec un prix initial souvent plus élevé."]},
  {heading:"Coût par page",paragraphs:["Ne comparez pas uniquement le prix de l’imprimante. Regardez le rendement annoncé des consommables, le prix des cartouches ou du toner et la disponibilité des références en Tunisie. Les rendements varient selon la couverture de la page. Une imprimante bon marché peut devenir coûteuse si les consommables sont rares."]},
  {heading:"Connexion et compatibilité",paragraphs:["Wi‑Fi, USB, impression mobile, recto verso automatique et chargeur de documents peuvent changer le confort d’utilisation. Vérifiez la compatibilité avec votre ordinateur et votre téléphone. Le recto verso réduit le papier, mais son fonctionnement varie selon les modèles et les formats pris en charge."]},
  {heading:"Avant de comparer",paragraphs:["Comparez la référence exacte, les consommables inclus, la garantie et les fonctions. Sur Soumly, utilisez la comparaison pour repérer les écarts entre boutiques, puis vérifiez le coût des cartouches et les conditions de livraison sur le site du marchand."]},
 ]},
 {slug:"comparer-prix-en-ligne-tunisie",title:"Comment comparer les prix en ligne en Tunisie",excerpt:"Une méthode simple pour comparer des offres équivalentes et éviter les faux écarts de prix.",category:"Méthode",readTime:"7 min",sections:[
  {heading:"Commencer par la référence",paragraphs:["Le nom commercial ne suffit pas toujours : capacité, couleur, mémoire, taille et région peuvent changer le produit. Copiez la référence fabricant lorsque c’est possible et comparez les caractéristiques essentielles. Un prix inférieur pour une autre variante n’est pas une économie si elle ne répond pas au même besoin."]},
  {heading:"Regarder le prix final",paragraphs:["Ajoutez livraison, installation, accessoires obligatoires et éventuels frais de paiement. Pour un gros appareil, le service de livraison et la mise en place peuvent modifier fortement le coût. Notez la date de consultation : les prix en ligne et la disponibilité évoluent rapidement."]},
  {heading:"Évaluer le marchand",paragraphs:["Vérifiez l’identité de la boutique, ses coordonnées, les conditions de garantie, le retour et les moyens de contact. Une offre très basse doit être examinée, pas automatiquement rejetée. Lisez la fiche du vendeur et confirmez qu’il s’agit d’un produit neuf, reconditionné ou d’occasion selon ce qui est annoncé."]},
  {heading:"Ce que fait Soumly",paragraphs:["Soumly rassemble des offres de boutiques tunisiennes et met en avant les écarts observés pour une même référence. Le comparateur ne garantit pas le stock au moment du clic : la page du marchand reste la source de décision. Notre méthode explique les règles de correspondance, les prix et les limites des données."]},
  {heading:"Éviter les mauvaises comparaisons",paragraphs:["Ne comparez pas une capacité différente, une garantie différente ou un pack différent comme s’il s’agissait du même produit. Gardez une capture ou une note du prix et de la date lorsque l’achat est différé. Cette discipline réduit les mauvaises surprises et rend la comparaison réellement utile."]},
 ]},
 {slug:"reconnaitre-vraie-promotion",title:"Comment reconnaître une vraie promotion",excerpt:"Les vérifications à faire avant de croire à une remise affichée en ligne.",category:"Méthode",readTime:"7 min",sections:[
  {heading:"Une remise n’est pas une preuve",paragraphs:["Un pourcentage barré peut comparer le prix actuel à un prix de référence qui n’est pas observable ou qui ne correspond plus au marché. Regardez le prix final, la référence exacte et la période de l’offre. Une bonne promotion est d’abord un produit adapté à votre besoin à un coût total intéressant."]},
  {heading:"Comparer plusieurs marchands",paragraphs:["Consultez plusieurs offres équivalentes et vérifiez les écarts. Si toutes les boutiques sont proches, une remise annoncée peut simplement refléter un ancien prix catalogue. Si une offre est nettement plus basse, examinez le stock, la garantie, les accessoires et la condition du produit avant de conclure."]},
  {heading:"Vérifier les conditions",paragraphs:["Les promotions peuvent être liées à une quantité, un moyen de paiement, un pack ou une période courte. Lisez les petites lignes et le panier final. Pour l’électroménager, confirmez les frais de livraison et d’installation ; pour l’électronique, confirmez la garantie et la version régionale."]},
  {heading:"Utiliser l’historique avec prudence",paragraphs:["Un prix observé aujourd’hui ne prouve pas le prix d’hier. Soumly affiche des données actuelles de comparaison et ne fabrique pas un historique de prix. Pour documenter une décision, notez vous-même le prix, la date, la référence et les conditions du marchand."]},
  {heading:"La bonne décision",paragraphs:["Une vraie promotion combine référence claire, prix final vérifiable, conditions compréhensibles et vendeur identifiable. Comparez la valeur d’usage, pas uniquement la remise affichée. La page Méthodologie détaille comment interpréter les offres présentes sur Soumly."]},
 ]},
 {slug:"choisir-ecouteurs-casques-bluetooth",title:"Guide des écouteurs et casques Bluetooth",excerpt:"Autonomie, confort, codecs, réduction de bruit et appels : choisir un modèle adapté à son quotidien.",category:"Audio",readTime:"7 min",sections:[
  {heading:"Écouteurs ou casque",paragraphs:["Les écouteurs sont compacts et pratiques pour les déplacements, tandis qu’un casque enveloppant offre souvent une meilleure autonomie et une écoute plus immersive. Le confort dépend de la forme de l’oreille, du poids et de la pression. Si vous portez l’appareil plusieurs heures, ce critère mérite plus d’attention qu’une fiche technique brillante."]},
  {heading:"Autonomie et recharge",paragraphs:["Comparez l’autonomie des écouteurs seuls et celle obtenue avec l’étui. Pour un casque, regardez le temps de recharge, la possibilité d’utiliser un câble et la disponibilité d’une batterie remplaçable. La réduction de bruit et le volume élevé peuvent réduire l’autonomie annoncée."]},
  {heading:"Son, codecs et réduction de bruit",paragraphs:["Les codecs compatibles doivent correspondre au téléphone ou à la source. La réduction de bruit active est utile dans les transports, mais son efficacité dépend du maintien et des fréquences. Un mode transparence améliore la perception des annonces et de l’environnement. Aucun chiffre de codec ne remplace un ajustement confortable."]},
  {heading:"Microphone et appels",paragraphs:["Si vous utilisez le casque pour le travail, vérifiez la qualité des microphones dans le vent et le bruit. La stabilité Bluetooth, le multipoint et la facilité de basculer entre deux appareils peuvent être plus utiles que des basses très présentes. Regardez les retours et la garantie plutôt que de supposer qu’un modèle premium convient à tous."]},
  {heading:"Comparer les références",paragraphs:["Vérifiez la génération, le format, la couleur et les accessoires inclus. Comparez les offres d’une même référence sur Soumly puis ouvrez le marchand pour confirmer la disponibilité et les conditions. Une remise sur une ancienne génération peut être intéressante si les fonctions recherchées sont présentes."]},
 ]},
 {slug:"choisir-smartphone-budget",title:"Comment choisir un smartphone selon son budget",excerpt:"Une méthode par usages et priorités pour choisir un téléphone sans dépasser son budget en Tunisie.",category:"Smartphones",readTime:"8 min",sections:[
  {heading:"Petit budget : prioriser l’essentiel",paragraphs:["Dans un budget serré, privilégiez un écran lisible, une batterie correcte, un stockage suffisant et une garantie claire. Une fiche avec beaucoup de caméras ne vaut pas nécessairement mieux. Vérifiez la fluidité des applications utilisées, la qualité des appels et la possibilité de recevoir des mises à jour."]},
  {heading:"Milieu de gamme : meilleur équilibre",paragraphs:["Le milieu de gamme offre souvent le meilleur compromis entre autonomie, écran, appareil photo et performance. Comparez la mémoire vive, le stockage et le suivi logiciel. Une puce plus récente peut être préférable à un ancien modèle plus puissant sur le papier si vous souhaitez garder le téléphone plusieurs années."]},
  {heading:"Budget supérieur : payer pour un besoin",paragraphs:["Un modèle plus cher peut apporter meilleure photo nocturne, écran plus lumineux, étanchéité, recharge plus rapide ou performances durables. Identifiez la fonction qui justifie la différence. N’achetez pas une capacité ou une caméra uniquement parce qu’elle est supérieure si votre usage ne l’exploite pas."]},
  {heading:"Promotions et générations",paragraphs:["Une ancienne génération peut devenir intéressante pendant une baisse réelle, mais vérifiez la durée de support, la batterie et la compatibilité réseau. Comparez la référence exacte et le prix final chez plusieurs boutiques. Une promotion affichée doit toujours être vérifiée sur la page du marchand."]},
  {heading:"La vérification finale",paragraphs:["Avant de commander, confirmez stockage, RAM, couleur, chargeur, garantie et état du produit. Sur Soumly, utilisez le nombre d’offres et l’écart de prix comme aide à la décision, puis consultez la boutique. Le meilleur choix est celui qui respecte le budget tout en couvrant votre usage pendant la durée prévue."]},
 ]},
];

export const guideBySlug = (slug: string) => editorialGuides.find((guide) => guide.slug === slug);
export const guideClosing = commonClosing;
