// AUTO-GENERATED by merge_stores. Do not edit by hand.
export const categories: string[] = [
	"596-smartphone-tunisie",
	"301-pc-portable-tunisie",
	"373-pc-de-bureau",
	"667-ecran-pc-tunisie",
	"338-casque-ecouteurs",
	"334-souris-informatique",
	"704-claviers",
	"457-climatiseur-tunisie-chaud-froid",
	"331-sac-a-dos-tunisie",
	"PC Portable",
];
